Variable:
  - Dataset/Generator/preprocessor_parameter

Pipeline:
  name: tcn
  tcn_parameters:
    num_joints_in: 17
    num_joints_out: 17
    in_features: 2
    channels: 1024
    filter_widths: [3, 3, 3, 3, 3]

Dataset:
  dataset: h36m
  filepath: data/h36m_cpn+detectron+gt_2d_normalized+unnormlized_gt_3d.npy
  train_subjects: "S1" #"S1,S5,S6,S7,S8"
  test_subjects: "S9" #"S9,S11"
  
  Generator:
    preprocessor: MA
    preprocessor_parameter: [1, 3, 5, 7, 9]
    
    keypoint: gt
    chunked: True
    normalized: True
    batch_size: 128
    receptive_field: 243
    padding: True
    length: 10

HyperParameters:
  epochs: 2
  lr: 0.01
  lr_decay: [0.99, 0.9, 0.8]
  lr_decay_step: [1, 10, 50]

Optimizer:
  optimizer: adam
  amsgrad: False

Process:
  amp: True
  cuda: True
  dynamic_learning: True